### ISSUE TITLE
Interval Syntax

### ISSUE THREAD

**Issue by gingerBill** [gingerBill/Odin#40]
Currently, Odin uses `..` for a half-closed interval: `a..b` from a, up to but not including b [a, b). This interval syntax is used for slicing and `for in` statements:

```
x[..]; // slice
x[a..b]; // low and high indices
x[a..b..c]; // low, high, and max indices
```
```
for x in 0..10 {}
// similar to 
for x := 0; x < 10; x++{}
```

The questions I have are:

* Should intervals just be "half-closed" or should they support open ranges too [a, b]? Should the syntax be `a..b` for open and `a..<b` for half-closed?
* Should an interval/range be a core type which could be can be passed around? 
* How do you specify an iteration to step at different ranges e.g. +2, -1, etc?

**Comment by kiljacken** [comment]
For the open vs half closed I'm generally for keeping the default half closed and then using a..=b for the completely open. It seems like half-closed is the more common use case because of zero-based indexing.

If you however end up going open by default, you could allow the whole quadfecta of combinations:

| Pattern | Meaning |
| --- | --- |
| `a .. b` | Both inclusive |
| `a<.. b` | `a` exclusive, `b` inclusive |
| `a ..<b` | `a` inclusive, `b` exclusive |
| `a<..<b` | Both exclusive |

**Comment by gingerBill** [comment]
That solve the clusivity problem if a < b. That syntax will not work for iterations with certain step sizes and going backwards. A c-style for loop does solve this issue but it's more "error prone":
```
for i := 0; i < 10; i++ {}
// vs
for i in 0..<10 {} // proposed syntax
```
```
for i := 9; i >= 0; i -= 2 {}
// How do you represent that?
```

Maybe the problem is that I shouldn't be thinking this way and maybe having so way of implementing "iterators" into the language is needed. But this then raises other questions. Should they be implemented like trait bundles or like coroutines? The traits option is something I do not wish to do. Coroutines could be a good option but this is an entirely different question/problem I want to tackle later.

**Comment by procedural** [comment]
I'll vote for leaving `..` for half-closed intervals because it's the most common case, at least for me (`0..len(x)`).

`for i in 0..num` covers simple loops, for other cases with different steps or revers iterations I write C-style loops, because a loop usually is not the problem to write correctly...

**Comment by gingerBill** [comment]
The other use for an interval could be with match statements:
```
match c {
case '0'..'9': // Handle number
case 'A'..'Z', 'a'..'z', '_': // Handle letter
}
```
However this _would_ require making `..` open as half-closed would not make sense for this particular case.

**Comment by procedural** [comment]
Indeed, then `..` for open and `..<` for half-closed will be fine. **But change it as soon as possible** because you'll break everyone's current apps with `0..len(x)` :)

**Comment by gingerBill** [comment]
This will mean I will need 6 different bounds checking procedures now rather than just the two (slice and substring). But I will try add this functionality and soon as possible. I will have make sure everyone knows the change has happened.

**Comment by procedural** [comment]
So `..` to `..<` change has happened! :) https://github.com/gingerBill/Odin/commit/a713e33

**Comment by procedural** [comment]
For people who have slices like `[..0]`, the new way is `[0..<0]`
